name: Build Redmi Note 12 A13-5.15.78 (KSUN+SUSFS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Setup deps
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget curl zip unzip bc bison flex \
          build-essential python3 python3-pip libssl-dev ccache \
          libncurses5-dev libncursesw5-dev

    - name: Download Proton Clang
      run: |
        mkdir clang
        wget -q https://github.com/kdrag0n/proton-clang/releases/download/20230717/proton-clang-20230717.tar.gz -O clang.tar.gz
        tar -C clang -xzf clang.tar.gz

    - name: Set environment
      run: |
        echo "PATH=$(pwd)/clang/bin:$PATH" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV

    - name: Clone KernelSU + SUSFS
      run: |
        # KernelSU
        git clone https://github.com/tiann/KernelSU.git -b main KernelSU_src
        cp -r KernelSU_src/kernel/* ./kernel/

        # SUSFS
        git clone https://github.com/chenxiaolong/susfs.git SUSFS_src
        patch -p1 < SUSFS_src/kernel.patch || true

    - name: Build kernel 5.15.78
      run: |
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        export CC=clang
        mkdir -p out

        # config cho Redmi Note 12 (tapas, Android 13, 5.15.78)
        make O=out gki_defconfig
        make O=out vendor/tapas_defconfig

        # build
        make O=out -j$(nproc)

    - name: AnyKernel3 package
      run: |
        git clone https://github.com/WildKernel/AnyKernel3
        cp out/arch/arm64/boot/Image AnyKernel3/
        cp out/arch/arm64/boot/dtb* AnyKernel3/ || true
        cd AnyKernel3
        zip -r9 ../wildkernel-redminote12-5.15.78-ksun-susfs.zip *

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: wildkernel-redminote12-5.15.78-ksun-susfs
        path: wildkernel-redminote12-5.15.78-ksun-susfs.zip
        compression-level: 0
