name: Build Redmi Note 12 A13-5.15.78 (KSUN+SUSFS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex git \
          libncurses5-dev libssl-dev python3 python3-pip unzip zip zlib1g-dev wget

    - name: Download Proton Clang
      run: |
        mkdir clang
        wget -q https://github.com/kdrag0n/proton-clang/releases/download/20230717/proton-clang-20230717.tar.gz -O clang.tar.gz
        tar -C clang -xzf clang.tar.gz

    - name: Set environment
      run: |
        echo "PATH=$(pwd)/clang/bin:$PATH" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$(pwd)/clang/bin:$PATH
        export CROSS_COMPILE=$(pwd)/clang/bin/aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=$(pwd)/clang/bin/arm-linux-gnueabi-
        
        make O=out vendor/tapas_defconfig
        make O=out -j$(nproc) CC=clang

    - name: Pack AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git -b master AnyKernel
        cp out/arch/arm64/boot/Image AnyKernel/
        cd AnyKernel
        zip -r9 ../RedmiNote12-KSUN-SUSFS-A13-5.15.78.zip *

    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: RedmiNote12-KSUN-SUSFS-A13-5.15.78
        path: RedmiNote12-KSUN-SUSFS-A13-5.15.78.zip
